whisper:
  # 默认实现为 faster-whisper。指定 `models\Whisper\faster-whisper` 目录下的模型名称
  model_size: large-v2
  # 计算类型。CUDA 使用 'float16'，CPU 使用 'float32'。
  compute_type: float16
  # 推理完成后是否卸载模型。
  enable_offload: true

bgm_separation:
  # UVR 模型，可选 ["UVR-MDX-NET-Inst_HQ_4", "UVR-MDX-NET-Inst_3"]
  model_size: UVR-MDX-NET-Inst_HQ_4
  # 推理完成后是否卸载模型。如果显存小于 16GB，建议设置为 true
  enable_offload: true
  # 加载背景音乐分离模型的设备，可选 ["cuda", "cpu", "xpu"]
  device: cuda

# 应用于 `cache` 目录的设置。`/bgm-separation` 的输出文件会存放在 `cache` 目录中，
# （你可以通过测试 `/bgm-separation` 接口查看实际生成的文件。）
# 你可以在此调整 `cache` 目录中文件的 TTL/清理频率。
cache:
  # TTL（生存时间），单位为秒，默认为 10 分钟
  ttl: 600
  # 清理频率，单位为秒，默认为 1 分钟
  frequency: 60
